# Generated by Django 3.1.2 on 2020-10-10 04:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEn',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'area_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorClassification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('classification_name', models.CharField(blank=True, max_length=90, null=True)),
                ('classification_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'indicator_classification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorUnitSubgroup',
            fields=[
                ('iusnid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indicator_unit_subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NiStDtbPoly',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('id_field', models.CharField(blank=True, db_column='id_', max_length=20, null=True)),
                ('dt_name', models.CharField(blank=True, max_length=40, null=True)),
                ('st_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parts_field', models.IntegerField(blank=True, db_column='parts_', null=True)),
                ('points_field', models.IntegerField(blank=True, db_column='points_', null=True)),
                ('length_field', models.FloatField(blank=True, db_column='length_', null=True)),
                ('area_field', models.FloatField(blank=True, db_column='area_', null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ni_st_dtb_poly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('subgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeperiod',
            fields=[
                ('timeperiod_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'timeperiod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ut_data',
                'managed': False,
            },
        ),
    ]
